{
    "0000": "General Success",
    "1000": "User logged in successfully",
    "1001": "OTP sent successfully",
    "1002": "OTP verification successfully",
    "1003": "You have an account with this Mobile Number or Email",
    "1004": "You have an account with mobile Number",
    "1005": "Please verify your mobile number and email",
    "1006": "MobileNumber already verified Please verify email",
    "1007": "Email already verified Please verify MobileNumber",
    "1008": "Your MobileNumber or email is already linked with",
    "1009": "Mobile number already verified",
    "1010": "Email already verified",
    "1011": "You can't Block the date.You have a bookings on that day",
    "1012": "Password updated successfully",
    "1013": "Blocked Date is already available",
    "1015": "You can't Inactive the Property Info",
    "1016": "You can't Inactive the Property",
    "1017": "You can't Book these dates these dates already blocked",
    "9001": "Service provider Location is not able to inactive",

    "9950": "UserID or Password is incorrect",
    "9951": "Your account is inactive",
    "9952": "Your account is blocked",
    "9953": "OTP sent failed",
    "9954": "OTP verification failed",
    "9955": "Please verify your mobileNumber and email before you signup",
    "9956": "Mobile Number is already exist",
    "9957": "Email is already exist",
    "9958": "Device Notify Token is already exist",
    "9959": "User ID already exist please use different UserID",
    "9960": "Profile Updated Successfully",
    "9961": "Post IDProof Scccessfully",
    "9962": "IDProof Updated Scccessfully",
    "9963": "Preferences Updated Scccessfully",
    "9979": "Invalid Current Password",
    "9980": "Invalid Kyc Detailes",
    "9985": "Rest password failed",
    "9986": "You do not have an account with this email / mobile number",
    "9987": "User ID is already taken",
    "9988": "You already have an acount with this email",
    "9989": "You already have an acount with this mobile number",
    "9990": "Invalid credentials",
    "9991": "Record delete failed",
    "9992": "Record update failed",
    "9993": "Record insertion failed",
    "9994": "Error in OTP generation",
    "9995": "Token expired",
    "9996": "Invalid User Token",
    "9997": "No data found",
    "9998": "Missing mandatory fields data",
    "9999": "An unexpected error occurred on the server side",
    "1010": "Support update successfully"
}
